added preview url
kanselarij-vlaanderen/press-releases-email-generator-service pull request #3
Opened 2021-09-29 18:47 UTC by MiVvlt

2021-09-29 20:42 UTC, Annelies-P commented on sparql-queries/press-release.sparql-queries.js
> +    console.log(pubTask)
mag weg?

2021-09-29 20:45 UTC, Annelies-P commented on sparql-queries/publication-task.sparql-queries.js
> +import { querySudo, updateSudo as update } from '@lblod/mu-auth-sudo';
ofwel 'querySudo as query' toevoegen ofwel de 'as update' voor updateSudo verwijderen zodat beiden op dezelfde manier geïmporteerd worden

2021-09-29 20:46 UTC, Annelies-P requested changes
zie 2 kleine comments

2022-05-26 09:25 UTC, erikap commented
Feature no longer requested

2022-05-26 09:25 UTC, closed without merging